# Generated by Django 5.2.8 on 2025-11-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('File', models.FileField(upload_to='music/')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
