# Generated by Django 5.2.8 on 2025-12-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='Date',
            new_name='created_at',
        ),
    ]
