# Generated by Django 5.2.8 on 2025-12-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_date_music_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='created_at',
            new_name='Date',
        ),
    ]
